# Minimal pairs to check
words_to_check = [
    'present', 'presents', 'PRESENT', 'PRESENTS', 
    'record', 'records', 'RECORD', 'RECORDS', 
    'conduct', 'conducts', 'CONDUCT', 'CONDUCTS', 
    'permit', 'permits', 'PERMIT', 'PERMITS', 
    'conflict', 'conflicts', 'CONFLICT', 'CONFLICTS', 
    'content', 'contents', 'CONTENT', 'CONTENTS', 
    'increase', 'increases', 'INCREASE', 'INCREASES', 
    'decrease', 'decreases', 'DECREASE', 'DECREASES', 
    'object', 'objects', 'OBJECT', 'OBJECTS', 
    'convert', 'converts', 'CONVERT', 'CONVERTS', 
    'export', 'exports', 'EXPORT', 'EXPORTS', 
    'import', 'imports', 'IMPORT', 'IMPORTS', 
    'protest', 'protests', 'PROTEST', 'PROTESTS', 
    'suspect', 'suspects', 'SUSPECT', 'SUSPECTS', 
    'digest', 'digests', 'DIGEST', 'DIGESTS', 
    'reject', 'rejects', 'REJECT', 'REJECTS', 
    'perfect', 'perfects', 'PERFECT', 'PERFECTS', 
    'insult', 'insults', 'INSULT', 'INSULTS', 
    'progress', 'progresses', 'PROGRESS', 'PROGRESSES', 
    'refuse', 'refuses', 'REFUSE', 'REFUSES', 
    'extract', 'extracts', 'EXTRACT', 'EXTRACTS', 
    'rebel', 'rebels', 'REBEL', 'REBELS', 
    'address', 'addresses', 'ADDRESS', 'ADDRESSES', 
    'subject', 'subjects', 'SUBJECT', 'SUBJECTS', 
    'project', 'projects', 'PROJECT', 'PROJECTS', 
    'contrast', 'contrasts', 'CONTRAST', 'CONTRASTS', 
    'transfer', 'transfers', 'TRANSFER', 'TRANSFERS', 
    'entrance', 'entrances', 'ENTRANCE', 'ENTRANCES'
]